#pragma config(Sensor, S1,     c1,             sensorEV3_Color)
#pragma config(Sensor, S2,     c2,             sensorEV3_Color)
#pragma config(Sensor, S3,     c3,             sensorEV3_Color)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int gray;

int calcBound2()
{
	int bound;
	int black = 0;
	int white = 0;

	for(int i = 0; i < 5; i++)
	{
		black += getColorReflected(c1);
		black += getColorReflected(c3);
		sleep(10);
	}

	setMotorSpeed(lm, 20);
	setMotorSpeed(rm, 20);
	sleep(500);
	setMotorSpeed(lm, 0);
	setMotorSpeed(rm, 0);

	for(int i = 0; i < 5; i++)
	{
		white += getColorReflected(c1);
		white += getColorReflected(c3);
		sleep(10);
	}

	bound = (white / 10 + black / 10) / 2;

	return bound;
}

task leftWheel()
{
	while(1)
	{
		if(getColorReflected(c1) >= gray)
				setMotorSpeed(lm, 40);
		else
				setMotorSpeed(lm, 0);
		sleep(10);
	}
}

task rightWheel()
{
	while(1)
	{
		if(getColorReflected(c3) >= gray)
				setMotorSpeed(rm, 40);
		else
				setMotorSpeed(rm, 0);
		sleep(10);
	}
}

task main()
{
	gray = calcBound2();
	startTask(rightWheel);
	startTask(leftWheel);
	sleep(10000);
	stopAllTasks();
}
