#pragma config(Sensor, S1,     c1,             sensorEV3_Color)
#pragma config(Sensor, S2,     c2,             sensorEV3_Color)
#pragma config(Sensor, S3,     c3,             sensorEV3_Color)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#define THRESHOLD 40

task main()
{
   while(1)
   {
      sleep(1);
      if(getColorReflected(c1) > THRESHOLD)
      {
         setMotorSpeed(lm, 30);
         setMotorSpeed(rm, 0);
      }
      else
      {
         setMotorSpeed(lm, 0);
         setMotorSpeed(rm, 30);
      }
   }
}
