#pragma config(Sensor, S1,     ts,             sensorEV3_Touch)
#pragma config(Sensor, S2,     gs,             sensorEV3_Gyro)
#pragma config(Sensor, S3,     cs,             sensorEV3_Color)
#pragma config(Sensor, S4,     ss,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void go(int s){
   setMotorSpeed(lm,s);
   setMotorSpeed(rm,s);
   sleep(3000);
}

void pointturn(){
   setMotorSpeed(lm, 50);
   setMotorSpeed(rm, -50);
   sleep(5000);
}

void swingturn(){
   setMotorSpeed(lm, 50);
   setMotorSpeed(rm, 0);
   sleep(5000);
}

void curveturn(){
   setMotorSpeed(lm, 50);
   setMotorSpeed(rm, 20);
   sleep(5000);
}

task main()
{
   go(50);
   go(-50);
   pointturn();
   swingturn();
   curveturn();
   playSound(soundBeepBeep);
   sleep(2000);

}
