#pragma config(Sensor, S1,     ts,             sensorEV3_Touch)
#pragma config(Sensor, S2,     gs,             sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     cs,             sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     ss,             sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          lm,            tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rm,            tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define Green 3
#define red 5

int color, speed = 40;

void go(int s)
{
	setMotorSpeed(lm, s);
	setMotorSpeed(rm, s);
}

task main()
{
	while(1)
	{
		go(speed);
		color = getColorName(cs);
		if(color == 5)
		{
			setMotorSpeed(lm, 0);
			setMotorSpeed(rm, 0);
			sleep(500);

			if(color == 3)
			{
				go(speed);
			}
		}
		if(color == 3)
		{
			go(speed);
		}
	}
}
